@startuml docker_stop
start
:**process_name**
**publish_port**/
:for **container_id** in $(docker container ls -a --no-trunc | awk 'FNR == 1 {next}{print $1}');
repeat
-> container_id;
    :**docker_inspect_json**=$(docker inspect "$**container_id**");
    :docker_stop_running "$**process_name**" "$**publish_port**" "$**container_id**" "$**docker_inspect_json**"|
repeat while (container_id)
stop
@enduml